version = 0.1

[default.deploy.parameters]
stack_name = "intervyu-lambda"
resolve_s3 = true
s3_prefix = "intervyu-lambda"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "AnthropicApiKey=\"\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
